[package]
name = "automatic-relations"
version = "0.1.0"
authors = ["Timothée Haudebourg <timothee.haudebourg@irisa.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terms = { path = "../terms" }
tree-automata = { path = "../tree-automata" }
crossbeam-channel = "*"
